# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

# ? Set DENO_DIR to an absolute or relative path on the runner.
env:
  DENO_VERSION: v1.39.1
  # DENO_DIR: my_cache_directory

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
        - os: ubuntu-latest
          cache_path: ~/.cache/deno/
        - os: macos-latest
          cache_path: ~/Library/Caches/deno/
        - os: windows-latest
          cache_path: ~\AppData\Local\deno\

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: cache deps
        uses: actions/cache@v3
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
