# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push
  pull_request

permissions:
  contents: read

jobs:
  # ? Set DENO_DIR to an absolute or relative path on the runner.
  # env:
  #   DENO_DIR: my_cache_directory

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.39.1

      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
    
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      uses: actions/checkout@v4

    - name: Cache Deno dependencies 
      uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ hashFiles('deno.lock') }}

    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Run tests
        run: deno test -A
