name: Slack Webhook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    name: "Status message after updates"
    runs-on: ubuntu-latest
    steps:
      - name: "Greetings!"
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Status Update:"
            blocks:
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "${{ github.event.pusher.username }} just pushed"
